#!/bin/bash

########################################################################
# Name:iptables-compare.sh
# Version:1.0
# Description: script usado para comparar dois arquivps iptables-save
# Author: Gustavo Scheffer
########################################################################


m_erro="Erro na sintax: iptables-compare.sh [arquivos_antigo] [arquivo_corrente]"
while getopts o:c: option
do
case "${option}"
in
o) old_file=${OPTARG};;
c) current_file=${OPTARG};;
*) Message=$m_erro;;
esac
done

if [ "$old_file" != "" ] && [ "$current_file" != "" ]; then
	echo "Comparando iptables-save's..."
	sleep 2
	clear
	echo ""
	echo "Este script e usado para comparar duas saídas do comando IPTABLES-SAVE. Se outros arquivos forem comparados,"
	echo "gerara inconsistencia!!!"

	echo "Nesta saída os arquivos são colocados lado a lado (old e current)"
	echo ""
	echo "LEGENDAS: "
	echo "----------------------------------------------"
	echo "'|'  ->  Significa que a linha foi alterada"
	echo "'>'  ->  Significa que esta linha foi adicionada"
	echo "'<'  ->  Significa que a linha foi alterada"
	echo ""
	echo "----------------------------------------------"
	diff -y $old_file $current_file | grep "|\|<\|>" | sed -e 's/# Completed.*//g' | sed -e 's/# Generated by iptables-save.*//g'
else
	echo ""
	echo "Este script e usado para comparar duas saídas do comando IPTABLES-SAVE. Se outros arquivos forem comparados,"
	echo "gerara inconsistencia!!!"
	echo ""
	echo $m_erro
fi



echo ""
echo ""